export interface AppointmentEntry {
  patientId: string;
  patientName: string;
  ageSex: string;
  appointmentDate: string;  // YYYY-MM-DD
  appointmentTime: string;  // HH:MM AM/PM
  department: string;
  departmentLocation: string;
  provider: string;
  officeLocation: string;
  visitType: "New" | "Follow-up" | "Consultation";
  bookingStatus: "Confirmed" | "Pending" | "Cancelled";
}

export const dummyAppointments: AppointmentEntry[] = [
  {
    patientId: "P1001",
    patientName: "John Doe",
    ageSex: "34/M",
    appointmentDate: "2025-11-10",
    appointmentTime: "9:30 AM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Corey McDonald",
    officeLocation: "Room 205B",
    visitType: "Follow-up",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1002",
    patientName: "Jane Smith",
    ageSex: "28/F",
    appointmentDate: "2025-11-10",
    appointmentTime: "1:45 PM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Corey McDonald",
    officeLocation: "Room 205B",
    visitType: "New",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1003",
    patientName: "Sam Clide",
    ageSex: "45/M",
    appointmentDate: "2025-11-11",
    appointmentTime: "7:30 AM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Liam Macintyre",
    officeLocation: "Room 204A",
    visitType: "Consultation",
    bookingStatus: "Pending",
  },
  {
    patientId: "P1004",
    patientName: "Janet Halworth",
    ageSex: "52/F",
    appointmentDate: "2025-11-11",
    appointmentTime: "9:00 AM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Liam Macintyre",
    officeLocation: "Room 204A",
    visitType: "Follow-up",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1005",
    patientName: "Alberto Ruiz",
    ageSex: "39/M",
    appointmentDate: "2025-11-12",
    appointmentTime: "4:00 PM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Martha Chen",
    officeLocation: "Room 207C",
    visitType: "New",
    bookingStatus: "Cancelled",
  },
  {
    patientId: "P1006",
    patientName: "Megan Fox",
    ageSex: "27/F",
    appointmentDate: "2025-11-13",
    appointmentTime: "9:15 AM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "David Kim",
    officeLocation: "Room 208A",
    visitType: "Consultation",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1007",
    patientName: "Lucas Brown",
    ageSex: "50/M",
    appointmentDate: "2025-11-14",
    appointmentTime: "2:30 PM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Elena Gonzalez",
    officeLocation: "Room 209B",
    visitType: "Follow-up",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1008",
    patientName: "Nina Patel",
    ageSex: "30/F",
    appointmentDate: "2025-11-15",
    appointmentTime: "8:00 AM",
    department: "Internal Medicine",
    departmentLocation: "Main Hospital Building - 2nd Floor",
    provider: "Mohammed Ali",
    officeLocation: "Room 210C",
    visitType: "New",
    bookingStatus: "Pending",
  },
  {
    patientId: "P1009",
    patientName: "Bob Adams",
    ageSex: "44/M",
    appointmentDate: "2025-11-10",
    appointmentTime: "10:15 AM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Kurt Clark",
    officeLocation: "Room 102A",
    visitType: "Consultation",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1010",
    patientName: "Alice Lee",
    ageSex: "36/F",
    appointmentDate: "2025-11-10",
    appointmentTime: "11:30 AM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Kurt Clark",
    officeLocation: "Room 102A",
    visitType: "Follow-up",
    bookingStatus: "Cancelled",
  },
  {
    patientId: "P1011",
    patientName: "Tom Harris",
    ageSex: "42/M",
    appointmentDate: "2025-11-12",
    appointmentTime: "2:00 PM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Brandon Funk",
    officeLocation: "Suite 16 — Pediatrics Wing",
    visitType: "New",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1012",
    patientName: "Tracy Mills",
    ageSex: "29/F",
    appointmentDate: "2025-11-13",
    appointmentTime: "5:30 PM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Sandra Ng",
    officeLocation: "Room 104B",
    visitType: "Consultation",
    bookingStatus: "Pending",
  },
  {
    patientId: "P1013",
    patientName: "David Smith",
    ageSex: "33/M",
    appointmentDate: "2025-11-14",
    appointmentTime: "8:30 AM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Olivia Martinez",
    officeLocation: "Room 105A",
    visitType: "Follow-up",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1014",
    patientName: "Anna Bell",
    ageSex: "38/F",
    appointmentDate: "2025-11-15",
    appointmentTime: "3:15 PM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Ryan Scott",
    officeLocation: "Room 106B",
    visitType: "New",
    bookingStatus: "Confirmed",
  },
  {
    patientId: "P1015",
    patientName: "Zoe Lin",
    ageSex: "26/F",
    appointmentDate: "2025-11-16",
    appointmentTime: "10:45 AM",
    department: "Family Medicine",
    departmentLocation: "Outpatient Clinic - Suite 14",
    provider: "Priya Singh",
    officeLocation: "Room 107C",
    visitType: "Consultation",
    bookingStatus: "Confirmed",
  },
];
