import { PatientRecord, NurseRecord } from "@/components/shared/nurse/shared-interface";

// Nurse Records
export const nurseRecords: NurseRecord[] = [
    {
        nurseId: "N001",
        nurseName: "Maria Santos",
        ageSex: "32/F",
        nursePosition: "Staff Nurse III",
        nurseSpecialty: "Medical-Surgical",
        nurseDepartment: "Internal Medicine",
        currentAssignment: "Ward 3A",
        signature: "M. Santos, RN"
    },
    {
        nurseId: "N002",
        nurseName: "John Reyes",
        ageSex: "28/M",
        nursePosition: "Staff Nurse II",
        nurseSpecialty: "Emergency Care",
        nurseDepartment: "Emergency Department",
        currentAssignment: "Ward 2B",
        signature: "J. Reyes, RN"
    },
    {
        nurseId: "N003",
        nurseName: "Catherine Lim",
        ageSex: "35/F",
        nursePosition: "Senior Staff Nurse",
        nurseSpecialty: "Cardiac Care",
        nurseDepartment: "Cardiology",
        currentAssignment: "Ward 4C",
        signature: "C. Lim, RN"
    },
    {
        nurseId: "N004",
        nurseName: "Roberto Cruz",
        ageSex: "30/M",
        nursePosition: "Staff Nurse II",
        nurseSpecialty: "Orthopedics",
        nurseDepartment: "Surgery",
        currentAssignment: "Ward 3A",
        signature: "R. Cruz, RN"
    },
    {
        nurseId: "N005",
        nurseName: "Ana Mendoza",
        ageSex: "29/F",
        nursePosition: "Staff Nurse III",
        nurseSpecialty: "Respiratory Care",
        nurseDepartment: "Pulmonology",
        currentAssignment: "Ward 2B",
        signature: "A. Mendoza, RN"
    }
];

// Patient Records with Vitals
export const patientRecords: PatientRecord[] = [
    {
        patientId: "P001",
        patientName: "Ricardo Dela Cruz",
        ageSex: "58/M",
        currentPhysician: "Dr. Angela Torres",
        currentWard: "Ward 3A",
        currentRoom: "301",
        chiefComplaint: "Chest pain and shortness of breath",
        diagnosis: "Acute Coronary Syndrome",
        allergies: "Penicillin, Shellfish",
        vitals: [
            {
                id: "V001",
                patientId: "P001",
                temperature: 37.2,
                pulseRate: 92,
                respirationRate: 22,
                systolicBP: 145,
                diastolicBP: 90,
                oxygenSaturation: 94,
                painLevel: 6,
                notes: "Patient reports crushing chest pain radiating to left arm. Anxious and diaphoretic.",
                dateTaken: new Date("2025-12-03"),
                timeTaken: "08:30",
                nurseId: "N003"
            },
            {
                id: "V002",
                patientId: "P001",
                temperature: 37.0,
                pulseRate: 85,
                respirationRate: 18,
                systolicBP: 138,
                diastolicBP: 88,
                oxygenSaturation: 96,
                painLevel: 3,
                notes: "Pain decreased after medication. Patient more comfortable.",
                dateTaken: new Date("2025-12-03"),
                timeTaken: "14:00",
                nurseId: "N003"
            },
            {
                id: "V003",
                patientId: "P001",
                temperature: 36.8,
                pulseRate: 78,
                respirationRate: 16,
                systolicBP: 132,
                diastolicBP: 82,
                oxygenSaturation: 97,
                painLevel: 1,
                notes: "Vitals stable. Patient resting comfortably.",
                dateTaken: new Date("2025-12-04"),
                timeTaken: "06:00",
                nurseId: "N001"
            }
        ]
    },
    {
        patientId: "P002",
        patientName: "Luisa Fernandez",
        ageSex: "42/F",
        currentPhysician: "Dr. Ramon Garcia",
        currentWard: "Ward 2B",
        currentRoom: "215",
        chiefComplaint: "Severe abdominal pain",
        diagnosis: "Acute Appendicitis",
        allergies: "None",
        vitals: [
            {
                id: "V004",
                patientId: "P002",
                temperature: 38.5,
                pulseRate: 105,
                respirationRate: 20,
                systolicBP: 128,
                diastolicBP: 78,
                oxygenSaturation: 98,
                painLevel: 8,
                notes: "Rebound tenderness in RLQ. Patient guarding abdomen. Awaiting surgical consult.",
                dateTaken: new Date("2025-12-05"),
                timeTaken: "11:20",
                nurseId: "N002"
            },
            {
                id: "V005",
                patientId: "P002",
                temperature: 38.2,
                pulseRate: 98,
                respirationRate: 18,
                systolicBP: 125,
                diastolicBP: 76,
                oxygenSaturation: 99,
                painLevel: 7,
                notes: "Pre-operative assessment. Patient NPO, IV started.",
                dateTaken: new Date("2025-12-05"),
                timeTaken: "15:45",
                nurseId: "N002"
            }
        ]
    },
    {
        patientId: "P003",
        patientName: "Eduardo Ramos",
        ageSex: "71/M",
        currentPhysician: "Dr. Patricia Santos",
        currentWard: "Ward 4C",
        currentRoom: "412",
        chiefComplaint: "Difficulty breathing and persistent cough",
        diagnosis: "Community Acquired Pneumonia",
        allergies: "Sulfa drugs",
        vitals: [
            {
                id: "V006",
                patientId: "P003",
                temperature: 39.1,
                pulseRate: 110,
                respirationRate: 28,
                systolicBP: 135,
                diastolicBP: 85,
                oxygenSaturation: 89,
                painLevel: 4,
                notes: "Labored breathing, crackles bilateral lower lobes. O2 started at 4L/min via nasal cannula.",
                dateTaken: new Date("2025-12-04"),
                timeTaken: "09:15",
                nurseId: "N005"
            },
            {
                id: "V007",
                patientId: "P003",
                temperature: 38.6,
                pulseRate: 102,
                respirationRate: 24,
                systolicBP: 130,
                diastolicBP: 82,
                oxygenSaturation: 92,
                painLevel: 3,
                notes: "Slight improvement after antibiotics. Still requires O2 support.",
                dateTaken: new Date("2025-12-05"),
                timeTaken: "07:30",
                nurseId: "N005"
            },
            {
                id: "V008",
                patientId: "P003",
                temperature: 38.0,
                pulseRate: 95,
                respirationRate: 22,
                systolicBP: 128,
                diastolicBP: 80,
                oxygenSaturation: 94,
                painLevel: 2,
                notes: "Breathing more comfortable. Cough productive with clear sputum.",
                dateTaken: new Date("2025-12-06"),
                timeTaken: "13:00",
                nurseId: "N005"
            }
        ]
    },
    {
        patientId: "P004",
        patientName: "Jennifer Tan",
        ageSex: "29/F",
        currentPhysician: "Dr. Michael Aquino",
        currentWard: "Ward 3A",
        currentRoom: "308",
        chiefComplaint: "Right ankle pain and swelling after fall",
        diagnosis: "Closed fracture, right ankle",
        allergies: "Latex",
        vitals: [
            {
                id: "V009",
                patientId: "P004",
                temperature: 36.7,
                pulseRate: 76,
                respirationRate: 14,
                systolicBP: 118,
                diastolicBP: 72,
                oxygenSaturation: 99,
                painLevel: 7,
                notes: "Swelling and ecchymosis noted on right ankle. Cast applied after reduction.",
                dateTaken: new Date("2025-12-06"),
                timeTaken: "16:20",
                nurseId: "N004"
            }
        ]
    },
    {
        patientId: "P005",
        patientName: "Antonio Villanueva",
        ageSex: "65/M",
        currentPhysician: "Dr. Elena Cruz",
        currentWard: "Ward 2B",
        currentRoom: "220",
        chiefComplaint: "Uncontrolled blood sugar levels and dizziness",
        diagnosis: "Type 2 Diabetes Mellitus, uncontrolled",
        allergies: "Aspirin",
        vitals: [
            {
                id: "V010",
                patientId: "P005",
                temperature: 36.9,
                pulseRate: 88,
                respirationRate: 16,
                systolicBP: 142,
                diastolicBP: 88,
                oxygenSaturation: 97,
                painLevel: 0,
                notes: "Blood glucose 320 mg/dL. Insulin therapy initiated. Patient counseled on diet.",
                dateTaken: new Date("2025-12-07"),
                timeTaken: "10:00",
                nurseId: "N001"
            },
            {
                id: "V011",
                patientId: "P005",
                temperature: 36.8,
                pulseRate: 82,
                respirationRate: 15,
                systolicBP: 135,
                diastolicBP: 84,
                oxygenSaturation: 98,
                painLevel: 0,
                notes: "Blood glucose improved to 180 mg/dL. Patient tolerating meals well.",
                dateTaken: new Date("2025-12-08"),
                timeTaken: "08:45",
                nurseId: "N001"
            }
        ]
    },
    {
        patientId: "P006",
        patientName: "Sofia Martinez",
        ageSex: "52/F",
        currentPhysician: "Dr. Roberto Flores",
        currentWard: "Ward 4C",
        currentRoom: "405",
        chiefComplaint: "Severe headache and blurred vision",
        diagnosis: "Hypertensive Crisis",
        allergies: "NSAIDs",
        vitals: [
            {
                id: "V012",
                patientId: "P006",
                temperature: 37.1,
                pulseRate: 98,
                respirationRate: 20,
                systolicBP: 185,
                diastolicBP: 115,
                oxygenSaturation: 96,
                painLevel: 8,
                notes: "Severe hypertension. Patient reports throbbing headache. IV antihypertensives started.",
                dateTaken: new Date("2025-12-07"),
                timeTaken: "14:30",
                nurseId: "N003"
            },
            {
                id: "V013",
                patientId: "P006",
                temperature: 37.0,
                pulseRate: 86,
                respirationRate: 18,
                systolicBP: 158,
                diastolicBP: 95,
                oxygenSaturation: 97,
                painLevel: 5,
                notes: "BP responding to treatment. Headache improving.",
                dateTaken: new Date("2025-12-07"),
                timeTaken: "18:00",
                nurseId: "N003"
            },
            {
                id: "V014",
                patientId: "P006",
                temperature: 36.9,
                pulseRate: 80,
                respirationRate: 16,
                systolicBP: 142,
                diastolicBP: 88,
                oxygenSaturation: 98,
                painLevel: 2,
                notes: "BP stabilized. Patient much improved. Switched to oral medications.",
                dateTaken: new Date("2025-12-08"),
                timeTaken: "09:00",
                nurseId: "N001"
            }
        ]
    },
    {
        patientId: "P007",
        patientName: "Miguel Santos",
        ageSex: "19/M",
        currentPhysician: "Dr. Sandra Reyes",
        currentWard: "Ward 2B",
        currentRoom: "218",
        chiefComplaint: "High fever and body malaise",
        diagnosis: "Dengue Fever",
        allergies: "None",
        vitals: [
            {
                id: "V015",
                patientId: "P007",
                temperature: 40.2,
                pulseRate: 115,
                respirationRate: 22,
                systolicBP: 105,
                diastolicBP: 68,
                oxygenSaturation: 97,
                painLevel: 5,
                notes: "High grade fever, myalgia, positive tourniquet test. Platelet count monitoring.",
                dateTaken: new Date("2025-12-08"),
                timeTaken: "12:00",
                nurseId: "N002"
            },
            {
                id: "V016",
                patientId: "P007",
                temperature: 39.5,
                pulseRate: 108,
                respirationRate: 20,
                systolicBP: 110,
                diastolicBP: 70,
                oxygenSaturation: 98,
                painLevel: 4,
                notes: "Fever slightly decreased. Increased oral fluid intake. Monitoring for warning signs.",
                dateTaken: new Date("2025-12-09"),
                timeTaken: "07:15",
                nurseId: "N005"
            }
        ]
    },
    {
        patientId: "P008",
        patientName: "Carmen Lopez",
        ageSex: "48/F",
        currentPhysician: "Dr. Antonio Reyes",
        currentWard: "Ward 3A",
        currentRoom: "305",
        chiefComplaint: "Severe lower back pain radiating to left leg",
        diagnosis: "Lumbar Disc Herniation",
        allergies: "Codeine",
        vitals: [
            {
                id: "V017",
                patientId: "P008",
                temperature: 36.8,
                pulseRate: 84,
                respirationRate: 16,
                systolicBP: 132,
                diastolicBP: 80,
                oxygenSaturation: 98,
                painLevel: 9,
                notes: "Severe pain rating 9/10. Limited mobility. Pain management initiated.",
                dateTaken: new Date("2025-12-09"),
                timeTaken: "10:30",
                nurseId: "N004"
            },
            {
                id: "V018",
                patientId: "P008",
                temperature: 36.7,
                pulseRate: 80,
                respirationRate: 15,
                systolicBP: 128,
                diastolicBP: 78,
                oxygenSaturation: 99,
                painLevel: 6,
                notes: "Pain decreased after medication and physical therapy consult scheduled.",
                dateTaken: new Date("2025-12-09"),
                timeTaken: "16:00",
                nurseId: "N004"
            }
        ]
    },
    {
        patientId: "P009",
        patientName: "Daniel Ocampo",
        ageSex: "38/M",
        currentPhysician: "Dr. Grace Pascual",
        currentWard: "Ward 4C",
        currentRoom: "418",
        chiefComplaint: "Severe vomiting and diarrhea",
        diagnosis: "Acute Gastroenteritis",
        allergies: "None",
        vitals: [
            {
                id: "V019",
                patientId: "P009",
                temperature: 37.8,
                pulseRate: 102,
                respirationRate: 18,
                systolicBP: 108,
                diastolicBP: 70,
                oxygenSaturation: 97,
                painLevel: 6,
                notes: "Dehydrated. Multiple episodes of vomiting and diarrhea. IV fluids started.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "05:45",
                nurseId: "N002"
            },
            {
                id: "V020",
                patientId: "P009",
                temperature: 37.3,
                pulseRate: 92,
                respirationRate: 16,
                systolicBP: 115,
                diastolicBP: 74,
                oxygenSaturation: 98,
                painLevel: 4,
                notes: "Improved hydration status. Tolerating clear liquids. Episodes decreased.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "14:00",
                nurseId: "N005"
            },
            {
                id: "V021",
                patientId: "P009",
                temperature: 37.0,
                pulseRate: 85,
                respirationRate: 15,
                systolicBP: 120,
                diastolicBP: 76,
                oxygenSaturation: 98,
                painLevel: 2,
                notes: "Significant improvement. No vomiting in last 6 hours. Started bland diet.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "20:30",
                nurseId: "N001"
            }
        ]
    },
    {
        patientId: "P010",
        patientName: "Rosa Navarro",
        ageSex: "76/F",
        currentPhysician: "Dr. Carlos Diaz",
        currentWard: "Ward 3A",
        currentRoom: "310",
        chiefComplaint: "Confusion and urinary symptoms",
        diagnosis: "Urinary Tract Infection with Delirium",
        allergies: "Sulfonamides, Eggs",
        vitals: [
            {
                id: "V022",
                patientId: "P010",
                temperature: 38.9,
                pulseRate: 96,
                respirationRate: 20,
                systolicBP: 142,
                diastolicBP: 86,
                oxygenSaturation: 95,
                painLevel: 3,
                notes: "Disoriented to time and place. Fever present. Urinalysis shows infection.",
                dateTaken: new Date("2025-12-09"),
                timeTaken: "11:00",
                nurseId: "N001"
            },
            {
                id: "V023",
                patientId: "P010",
                temperature: 38.2,
                pulseRate: 88,
                respirationRate: 18,
                systolicBP: 138,
                diastolicBP: 82,
                oxygenSaturation: 96,
                painLevel: 2,
                notes: "Antibiotics started. Mental status slightly improved. Family at bedside.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "08:00",
                nurseId: "N004"
            },
            {
                id: "V024",
                patientId: "P010",
                temperature: 37.5,
                pulseRate: 82,
                respirationRate: 16,
                systolicBP: 135,
                diastolicBP: 80,
                oxygenSaturation: 97,
                painLevel: 1,
                notes: "Fever resolving. Patient more alert and oriented. Responding well to treatment.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "17:30",
                nurseId: "N004"
            },
            {
                id: "V025",
                patientId: "P010",
                temperature: 37.1,
                pulseRate: 78,
                respirationRate: 15,
                systolicBP: 132,
                diastolicBP: 78,
                oxygenSaturation: 98,
                painLevel: 0,
                notes: "Significant improvement. Oriented x3. Ambulating with assistance.",
                dateTaken: new Date("2025-12-10"),
                timeTaken: "22:00",
                nurseId: "N001"
            }
        ]
    }
];